grafana/mcp-grafana

- .github/workflows/release.yml
- pyproject.toml
This follows the docs linked below to publish to TestPyPI
on all pushes and to PyPI on tag pushes, using the
Trusted Publisher authentication method.
- https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#separate-workflow-for-publishing-to-testpypi
- https://docs.astral.sh/uv/guides/publish/#publishing-your-package
> ci: set up pipeline to publish releases to PyPI

- .github/workflows/release.yml
Taken directly from https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#signing-the-distribution-packages.
> ci: also create GitHub releases with signed builds

- .github/workflows/python.yml
- pyproject.toml
- src/mcp_grafana/grafana_types.py
- uv.lock
And run tests across all Python versions.
> fix: allow Python 3.10, 3.11 or 3.12

- .github/workflows/python.yml
This makes sure the lock file is up-to-date.
> ci: use --locked flag in uv sync in CI

- pyproject.toml
- uv.lock
The only significant change is supporting earlier versions of Python.
> chore: bump version 0.1.0 -> 0.1.1

- pyproject.toml
- uv.lock
Contains a [bugfix] for tools with integer parameters.
[bugfix]: https://github.com/modelcontextprotocol/python-sdk/pull/142
> chore: bump mcp dependency to 1.2.1

- pyproject.toml
- uv.lock
The only change is a bump of the mcp dependency.
> chore: bump version 0.1.1 -> 0.1.2

- .github/workflows/python.yml
- pyproject.toml
- uv.lock
We use enum.StrEnum for our Transport in the CLI which is only
available in 3.11 and above, so we need to bump the minimum Python
version to 3.11.
Also run tests against 3.13 in CI.
> fix: bump requires-python to >=3.11

- tools/datasources.go
- tools/incident.go
- tools/incident_integration_test.go
- tools/incident_test.go
List incidents and list datasources can use a lot more context than necessary when returning results. For dashboards use a custom struct that only returns a few fields. For incidents use the preview incident endpoint which returns a more concise format.
> Limit the amount of data returned for list tools

- Makefile
Example output (minus some colours):
```
❯ make help
Usage: make [target]
Targets:
build-image                    Build the Docker image.
help                           Print this help message.
lint                           Lint the Go code.
run                            Run the MCP server in stdio mode.
run-sse                        Run the MCP server in SSE mode.
test-all                       Run the Go unit and integration tests.
test                           Run the Go unit tests.
```
> chore: improve Makefile with help, descriptions and run-sse target

- mcpgrafana.go
- mcpgrafana_test.go
Prior to this commit, the MCP server wasn't respecting the
`GRAFANA_URL` and `GRAFANA_API_KEY` environment variables when running in
SSE mode, and was expecting them to be passed in via headers
(which is admittedly non-standard).
This commit adds a fallback to the environment variables if the
headers aren't present.
Relates to #40.
> feat: fallback to environment variables in SSE mode

- cmd/mcp-grafana/main.go
Prior to this we would set the base URL of the SSE server to the
address of the HTTP server. This isn't quite right because the
address on which the server listens isn't always the same as the
one which the client connects to; for example, in Docker we might
set the address to 0.0.0.0 but the client will connect to localhost.
Since most clients will verify that the endpoint sent by the initial
SSE handshake matches the address of the server they connect to, they
raise an error when they see that `localhost` doesn't match `0.0.0.0`.
This commit fixes that by just not setting the base URL at all. This
results in the initial message just looking like this:
```
event: endpoint
data: /message?sessionId=c96d5796-92f3-42f3-aa51-555aa21e1c8f
```
which matches what the Python SDK does (see …
> fix: don't set base URL of SSE server

- README.md
- cmd/mcp-grafana/main.go
- docker-compose.yaml
- tests/loki-config.yml
- tests/promtail-config.yml
- tests/provisioning/datasources/datasources.yaml
- tools/datasources_test.go
- tools/loki.go
- tools/loki_test.go
Related to [this issue](https://github.com/grafana/mcp-grafana/issues/33)
In this PR we are adding tools to:
- get label names
- get label values
- get stats
- run queries (either metric or log queries)
from Loki datasources. 
TODO:
> Add loki tools

- README.md
- cmd/mcp-grafana/main.go
- go.mod
- go.sum
- testdata/provisioning/alerting/alert_rules.yaml
- tools/alerting.go
- tools/alerting_test.go
- tools/prometheus.go
- tools/prometheus_test.go
This PR adds new tools to interact with Grafana Alerting:
- `list_alert_rules`: List all alert rules
- `get_alert_rule_by_uid`: Get information about a specific alert rule
> Alerting: Add support for getting alert rule information

- tools/datasources.go
- tools/datasources_test.go
To reduce the amount of context passed back to the agent it is now possible to do client-side filtering of all datasources to just the type desired. This is implemented using case insensitive Contains so that the type does not have to be perfect.
Closes: #52
> Allow filtering of datasources by type

- tools/incident.go
- tools/incident_integration_test.go
Adds tool to get one incident if an ID is provided. 
Also iterates a bit on the incident prompts as the model was always very keen to add an activity item to the incident 🙄 without having a request for it.
> Add tool get incident

- testdata/provisioning/alerting/contact_points.yaml
- tools/alerting.go
- tools/alerting_test.go
Added listContactPoints function to fetch and paginate contact points from Grafana. 
Supports filtering by name and returns summarized data (UID, Name, Type). 
Tests included for pagination, filtering, and invalid parameters.
> Add listing all contact points with pagination

- go.mod
- go.sum
- tools/oncall.go
- tools/oncall_cloud_test.go
This PR adds support to:
* get schedules by teamID  
* getCurrentOnCallUsers to return the name or username of the user instead of an ID
> Oncall tools improvements

- tools/prometheus.go
> fix: mention that stepSeconds and endRfc3339 are required for Prometheus range queries

- README.md
- tools/alerting.go
- tools/alerting_client.go
- tools/alerting_client_test.go
- tools/alerting_test.go
Updates the existing alert tools to retrieve state information (firing, normal, pending, etc.) for alerts.
Since the Alerting provisioning API does not expose this information, I had to add a custom alerting client that uses the same [API](https://github.com/grafana/grafana/blob/87e69e13493899cfa3083ba9327dfeb5a9a4b093/pkg/services/ngalert/api/tooling/definitions/prom.go#L15) used by the UI. This API is not part of the officially stable public APIs, but the client makes it possible to add other endpoints, for example alert state history.
This API supports pagination of the alert rule groups, but I haven't added anything for it yet. Can do a follow-up :)
> Add state retrieval for alert rules

- .github/workflows/go.yml
- Makefile
- README.md
- cmd/linters/jsonschema/main.go
- internal/linter/jsonschema/README.md
- internal/linter/jsonschema/jsonschema_lint.go
- internal/linter/jsonschema/jsonschema_lint_test.go
- tools/alerting.go
- tools/datasources.go
- tools/incident.go
- tools/loki.go
- tools/oncall.go
- tools/prometheus.go
Commas in jsonschema `description` fields inside struct field tags need
to be escaped; otherwise, they're treated as another field and the
description is silently truncated. This commit fixes all instances of
that, and adds a linter which checks for the presence of any unescaped
commas in the `jsonschema` descriptions. The linter also includes a
`--fix` mode to automatically fix any issues, and is integrated in CI so
we should catch this in future. (Thanks Claude & Zed!)
> Fix commas in JSONSchema descriptions and add linter

- Makefile
Issue: https://github.com/grafana/mcp-grafana/issues/103
> fix: go run multiple packages

- README.md
- cmd/mcp-grafana/main.go
- go.mod
- mcpgrafana.go
- tools/cloud_testing_utils.go
- tools/incident_integration_test.go
- tools/oncall_cloud_test.go
- tools/sift.go
- tools/sift_cloud_test.go
Adding Sift tools for 
* Create Investigation 
* List investigations with a limit parameter
* Get investigation 
* Get analyses
* Run ErrorPatternLogs Sift Check
* Run SlowRequests Sift Check
Also there is cloud test added checking the get tools for sift. 
I initially created separate tools for basic Sift API operations (create/get investigations) to reduce code duplication. However, for specific checks like ErrorPatternLogs and SlowRequests, I created dedicated tools that handle the entire workflow internally.
When running ErrorPatternLogs in Sift, the process involves:
1. Creating an investigation with specific tags to limit checks (eg: ErrorPatternLogs)
2. Getting investigation details when complete
3. Retrieving the ErrorPatternLog analysis using the analysis ID from investigation …
> Sift tools

- README.md
There's now a prebuilt Docker image at
https://hub.docker.com/r/mcp/grafana which we should suggest in the README.
Fixes #106.
> docs: document Docker image option for MCP server

- README.md
- tools/dashboard.go
- tools/dashboard_test.go
Adds a new tool to update/create a dashboard. Also added a warning/disclaimer about context windows, which will be solved longer-term with https://github.com/grafana/mcp-grafana/issues/101.
Closes https://github.com/grafana/mcp-grafana/issues/90.
> Add tool to update/create a dashboard

- README.md
VSCode doesn’t auto-discover custom SSE endpoints, so this config explicitly sets the MCP server URL. Prevents silent failures and confusion when the connection to /sse isn’t resolved automatically.
> docs: add note for vscode

- tools/sift.go
Adding some actual log examples so the model can get full context and skip querying the logs separately.
> ErrorPatternLogs query log examples along with the patterns

- .github/workflows/go.yml
- Makefile
Added a git action for the python e2e tests and also a schedule for the workflow on a daily basis. 
e2e tests are not mandatory to merge for now as we are still iterating and they are still a bit flaky but at least we can get notified when something is systematically failing. 
Added a make command for the e2e tests but I got some weird results so I didn't use it in the git action. I can't iterate on this now though. I can do it on a separate PR. 
We can probably exclude the other actions from running on a daily basis if we think it's too much.
> Add GitHub action for e2e tests

- tools/sift.go
Details can be nil if, for example, no logs are found. This PR prevents this tool from panicking.
> Prevent panic if didn't find patterns.

- Makefile
Builds the mcp-grafana binary and puts it in 'dist'.
> feat: add build target to Makefile

- tools/cloud_testing_utils.go
- tools/sift.go
- tools/sift_cloud_test.go
This adds a cloud integration test for the functions underlying the error pattern tool.
The commits are pretty atomic so it might be worth checking them out independently, but it's basically:
- add some logs when creating an investigation (note: we don't log any sensitive stuff, just investigation request/response and some IDs really)
- include a Grafana client in the test context, required to get Loki datasource IDs so we can fetch some examples
- when testing analysis stuff, rather than fetching just 1 investigation, fetch 10 in case the first has no analyses (which can happen if the investigation refused to start due to lack of matching log streams etc)
- add the actual test.
I had hoped this would find the cause of #123 but so far no dice :thinking:
> test: add test case for finding log error patterns

- mcpgrafana.go
- tools/cloud_testing_utils.go
- tools/sift.go
- tools/sift_cloud_test.go
There was a bunch of duplicated code when creating the Grafana client from
context, and I want to be able to do this in tests too, so this just refactors
the code for later.
> refactor: extract Grafana Client creation from context functions

- tools/alerting.go
- tools/asserts.go
- tools/dashboard.go
- tools/datasources.go
- tools/incident.go
- tools/loki.go
- tools/oncall.go
- tools/prometheus.go
- tools/search.go
- tools/sift.go
Add the read-only, idempotent, and destructive hint annotations to tools
where appropriate.
Co-authored-by: Luccas Quadros <luccas.quadros@grafana.com>
> feat: add more annotations to tools

- tools/asserts.go
This was just missed off the original OBO PR.
Should fix the auth issues mentioned in #134.
> fix: pass OBO auth to asserts client, if available

- .github/workflows/go.yml
GitHub secrets can't be used by actions in forks so tests are failing.
Also, this is now Grafana policy.
> ci: use Vault for secrets, not GitHub CI

- cmd/mcp-grafana/main.go
Description: Optional flag for setting a base path prefix for the SSE server. 
Explanation: I needed to add this to run the MCP SSE server along with other MCP servers as containers behind a single HTTP proxy. 
If there's a better way to do this let me know, I have little experience with MCP :)
fixes issue #138
> feat: add base-path flag for sse server

- docker-compose.yaml
- testdata/prometheus-entrypoint.sh
- testdata/prometheus-seed.yml
- tools/prometheus_test.go
This PR enhances the Docker Compose setup for development and testing by adding support for pre-seeding Prometheus with recording rule data. This change:
1. Modifies the Prometheus service in our `docker-compose.yaml` to use a custom entrypoint script
2. Adds a backfilling mechanism that generates 5 hours of historical data for a test recording rule
3. Re-enables a previously skipped Prometheus range query test that now has sufficient historical data to work with
- Created a custom entrypoint script (`testdata/prometheus-entrypoint.sh`) that:
- Starts Prometheus initially to make its API available
- Uses `promtool tsdb create-blocks-from rules` to backfill 5 hours of data for a simple test recording rule
- Restarts Prometheus to ensure the backfilled data is immediately available
- Added …
> Added seed data to prometheus

- tools/prometheus_unit_test.go
The tests for parsing relative time strings were failing due to
calendar arithmetic. This commit fixes the tests and adds a special
case for month and year calculations.
> fix: fix test for relative time calculations

- mcpgrafana.go
- mcpgrafana_test.go
When constructing the Grafana client we need to ensure that it doesn't
try to use HTTPS when the final Grafana URL scheme is HTTP.
This particularly affects the case where the Grafana URL is not
provided and the server is running on SSE mode. This is because:
- in stdio mode we use `ExtractGrafanaClientFromEnv`, which falls
back to explicitly using the `defaultGrafanaURL` variable if the
GRAFANA_URL environment variable is not set, so a non-empty value
is passed to `NewGrafanaClient`
- in SSE mode we use `ExtractGrafanaClientFromHeaders`, which does not
fall back to `defaultGrafanaURL` and instead passes an empty string,
therefore relying on the `NewGrafanaClient` to use the default
schemes.
Fixes #162.
> fix: always fixup schemes of Grafana client based on final Grafana URL

- cmd/mcp-grafana/main.go
Relates to #177 
Previously, the panic message excluded 'streamable-http', causing confusion. This PR adds it to the transport flag help text and error message to reflect support.
> refactor: include 'streamable-http' in transport-related messages

- .gitignore
- Makefile
- docker-compose.yaml
Quality of life fixes. Both because this is something I need and because it seems like it is likely to be helpful if the build is more reproducible. The docker changes are because those docker features are deprecated, they just still happen to work on macs
> fix: quality of life fixes

- README.md
- cmd/mcp-grafana/main.go
- examples/tls_example.go
- mcpgrafana.go
- tls_test.go
- tools/alerting_client.go
- tools/asserts.go
- tools/loki.go
- tools/prometheus.go
- tools/sift.go
This commit adds TLS configuration capabilities to the consolidated GrafanaConfig struct, allowing custom certificates for all HTTP clients used by the MCP server.
Changes:
- Add TLSConfig struct with CertFile, KeyFile, CAFile, and SkipVerify fields
- Integrate TLSConfig into GrafanaConfig struct
- Add TLS CLI flags to cmd/mcp-grafana/main.go
- Update all HTTP clients (Grafana, Incident, Loki, Prometheus, Sift, Asserts) to use custom TLS configuration when available
- Add TLS helper methods: CreateTLSConfig() and HTTPTransport()
- Include TLS example and test files
- Update README with comprehensive TLS configuration documentation
The TLS configuration is applied consistently across all clients, providing a unified approach to certificate management for secure Grafana environments.
Fixes …
> feat: add TLS configuration support to consolidated GrafanaConfig

- .goreleaser.yaml
Our `main.version` variable is no longer just a string, it's a
`sync.Once`, which means that it cannot be overridden by an
ldflags value. This commit updates the goreleaser config to
specify a custom value for 'ldflags', which removes the
`main.version` variable from the defaults.
> fix: remove main.version from goreleaser ldflags

- .github/workflows/e2e.yml
- Makefile
- README.md
- docker-compose.yaml
- mcpgrafana.go
- mcpgrafana_test.go
- tests/conftest.py
- tools/alerting_client.go
- tools/asserts.go
- tools/cloud_testing_utils.go
- tools/datasources_test.go
- tools/loki.go
- tools/oncall.go
- tools/prometheus.go
- tools/pyroscope.go
- tools/sift.go
Implements #256
Supports connecting via [basic auth](https://grafana.com/docs/grafana/latest/developers/http_api/authentication/#basic-auth) if the instance supports it. 
Configured via either
- Environment variables
* `GRAFANA_USERNAME`
* `GRAFANA_PASSWORD`
- HTTP Headers using standard HTTP basic auth
Works locally when connecting to grafana instance that has basic auth
> Support username/password authentication

- README.md
- cmd/mcp-grafana/main.go
- go.mod
- go.sum
mcp-go v0.39.0 adds support for https when using the streamable-http
transport. This commit adds support for configuring the server to
serve https using custom certificates via the CLI.
Fixes #244.
> feat: add support for https when using streamable-http transport

- mcpgrafana.go
Before this we were always using the old GRAFANA_API_KEY env var rather
than checking the GRAFANA_SERVICE_ACCOUNT_TOKEN first.
Fixes #278.
> fix: correctly get auth header from new env var

- .goreleaser.yaml
- gemini-extension.json
This commit adds a gemini-extension.json config file to the repo,
following the instructions in the [Gemini CLI docs][docs].
[docs]: https://github.com/google-gemini/gemini-cli/blob/main/docs/extension-releasing.md
> chore: add Gemini extension config
